### PR TITLE
When unmarking, only redraw highlights canvas

### PR DESCRIPTION
**Pull request by joshlory**
This gives a ~10x speed improvement when clearing highlights.

### CODE REVIEW

**Comment by cpirich** [comment]
Looks good, but it looks like a separate, existing bug is that `unmark` doesn't redraw at all. Do you want to fix this at the same time?

**Comment by joshlory** [comment]
Good catch, fixed in d20ac9ba835569abf9671e75272b741ff027de10.

**Comment by cpirich** [comment]
LGTM - should I merge?

**Comment by joshlory** [comment]
Yes, thank you!

**Pull request merged**
