### PR TITLE
Allow users to abort drags by replacing the block where they found it

### PR DESCRIPTION
**Pull request by dabbler0**
Change to `controller.coffee` to abort a drag if the user is hovering over the grayed-out block that represents the place they picked up the block. I don't know if this is a good UI decision -- thoughts?

### CODE REVIEW

**Comment by davidbau** [comment]
Nice comments.  A good case.  Consider adding a test of drag-editing including drag-to-self to uitest.html?

**Comment by davidbau** [comment]
BTW, a different usability feature that would be very nice (I see students running into it all the time):

After replacing a text socket by dragging a block on top of it, we should have the socket secretly remember the old text that was replaced.  If you pull the block back out of the socket, we should default the text to the remembered old value rather than the empty string.

Reason: it's way too easy to drop the wrong block into the wrong place.  And when you drop it into a text socket, you lose the carefully chosen text that used to be in the socket.   This would make it easy to "undo" the errant drop by dragging the block back out.

**Comment by sfilman** [comment]
@davidbau I've also run into that issue a bunch and agree it would be great to fix. We've added a row to the tracking spreadsheet.

**Comment by davidbau** [comment]
Nice test.  Simulating clicks isn't so bad, right?  A valuable thing to do!  LGTM.

**Comment by davidbau** [comment]
@sfilman - cool, thanks.

**Pull request merged**
